apiVersion: apps/v1
kind: Deployment
metadata:
  name: gstore-sales
  labels:
    app: gstore-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gstore-application
  template:
    metadata:
      labels:
        app: gstore-application
    spec:
      containers:
        - name: my-container
          image: "gandhicloudlab/cpro-bankweb:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9030
              protocol: TCP
            - name: https
              containerPort: 8082
              protocol: TCP
